"""Add password hash to users

Revision ID: 239d58cef455
Revises: c9e75fb97935
Create Date: 2026-09-19 13:16:34.001330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239d58cef455'
down_revision = 'c9e75fb97935'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'password_hash',
                sa.String(length=255),
                nullable=True
            )
        )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
